import Head from "next/head";
import Image from "next/image";

import { Cards } from "components/Cards";
import { WelcomeMessage } from "components/WelcomeMessage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
        <WelcomeMessage />

        <p className="my-8 text-center md:my-16 font-size-3">
          Get started by editing{" "}
          <code className="code">pages/index.js</code>
        </p>

        <Cards />

      </main>

      <footer>
        <a
          className="flex-center"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-4 ml-2 flex-center">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
